# Site Settings
locale: "en-US"
title: "Claire L. O'Connell"
description: "Behavioral ecologist, ornithologist."
url: "https://claireloconnell.github.io"
baseurl: "" 
repository: "claireloconnell/claireloconnell.github.io"

# Site Author
# This points to the "claire" block in your _data/authors.yml
#author: claire 
# Site Author - The following control what appear as part of the author content on the side bar.
#               If a field is blank the icon and link will not appear, otherwise it will be shown.
#               Additional customization can be done by editing /_includes/author-profile.html
author: 
  # Biographic information
  name: "Claire L. O'Connell, PhD"
  uri: "https://claireloconnell.github.io"
  email: "oconneca@mail.uc.edu"
  bio: "Behavioral ecologist and ornithologist."
  avatar: "/images/Profile_Picture_Defense.jpg" # Ensure this path is correct!
  twitter: "clairakeet"
  github: "claireloconnell"
  googlescholar: "https://scholar.google.com/citations?user=qMVBRjMAAAAJ&hl=en"
  orcid: "0000-0002-3852-3021"

# Theme Settings
remote_theme: "mmistakes/minimal-mistakes@master"
minimal_mistakes_skin: "default" # or your preferred skin

# Profile settings
breadcrumb: false
words_per_minute: 160

# Analytics
analytics:
  provider: "google-universal"
  google:
    tracking_id: ""

# Social Sharing (Default images)
twitter:
  username: "clairakeet"
og_image: "/assets/images/home/Header.png"


# Reading Files
include:
  - .htaccess
  - _pages
  - files
exclude:
  - "*.sublime-project"
  - "*.sublime-workspace"
  - .asset-cache
  - .bundle
  - .jekyll-assets-cache
  - .sass-cache
  - CHANGELOG
  - Capfile
  - Gemfile
  - Gruntfile.js
  - LICENSE
  - README
  - Rakefile
  - assets/js/_main.js
  - assets/js/plugins
  - assets/js/vendor
  - config
  - gulpfile.js
  - log
  - node_modules
  - package.json
  - tmp
  - vendor
keep_files:
  - .git
  - .svn
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"


# Conversion
markdown: kramdown
highlighter: rouge
lsi: false
excerpt_separator: "\n\n"
incremental: false


# Markdown Processing
kramdown:
  input: GFM
  hard_wrap: false
  auto_ids: true
  footnote_nr: 1
  entity_output: as_char
  toc_levels: 1..6
  smart_quotes: lsquo,rsquo,ldquo,rdquo
  enable_coderay: false


# Collections
collections:
  teaching:
    output: true
    permalink: /:collection/:path/
#  publications:
 #   output: true
#    permalink: /:collection/:path/
  publications: 
    output: true # Jekyll will generate pages for each publication
    permalink: /:collection/:title/ # This controls the URL for each publication page
  portfolio:
    output: true
    permalink: /:collection/:path/
  talks:
    output: true
    permalink: /:collection/:path/
  press:
    output: true
    permalink: /:collection/:path/

# Defaults
defaults:
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single
      author_profile: true
  # _teaching
  - scope:
      path: ""
      type: teaching
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _publications
  - scope:
      path: ""
      type: publications
    values:
      layout: single
      author_profile: true
      share: true
      comments: true
  # _portfolio
  - scope:
      path: ""
      type: portfolio
    values:
      layout: single
      author_profile: true
      share: true
      comment: true
  # _talks
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
      author_profile: true
      share: true
  # _press
  - scope:
      path: ""
      type: press
    values:
      layout: single
      author_profile: true
      share: true
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      layout: single
      author_profile: true
      read_time: false
      comments: true
      share: true
      related: true

# Sass/SCSS
sass:
  sass_dir: _sass
  style: compressed # http://sass-lang.com/documentation/file.SASS_REFERENCE.html#output_style


# Outputting
permalink: /:categories/:title/
# paginate: 5 # amount of posts to show
# paginate_path: /page:num/
timezone: America/Los_Angeles # http://en.wikipedia.org/wiki/List_of_tz_database_time_zones


# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
#  - jekyll-paginate
#  - jekyll-sitemap
#  - jekyll-gistsf
  - jekyll-feed
  - jekyll-include-cache
#  - jekyll-redirect-from
# mimic GitHub Pages with --safe
whitelist:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji


# Archives
#  Type
#  - GitHub Pages compatible archive pages built with Liquid ~> type: liquid (default)
#  - Jekyll Archives plugin archive pages ~> type: jekyll-archives
#  Path (examples)
#  - Archive page should exist at path when using Liquid method or you can
#    expect broken links (especially with breadcrumbs enabled)
#  - <base_path>/tags/my-awesome-tag/index.html ~> path: /tags/
#  - <base_path/categories/my-awesome-category/index.html ~> path: /categories/
#  - <base_path/my-awesome-category/index.html ~> path: /
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/
# https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /categories/:name/
#     tag: /tags/:name/


# HTML Compression
# - http://jch.penibelst.de/
compress_html:
  clippings: all
  ignore:
    envs: development
   
